version: '2.1'

services:
  app:
    restart: unless-stopped
    build:
      context: ./app
      dockerfile: Dockerfile-dev
      args:
        # internal ports
        - PORT=3000
        - DEBUG_PORT=9229
    ports:
      # map external ports to internal ports
      - ${PORT:-3000}:3000
      - ${DEBUG_PORT:-9229}:9229
    env_file:
      - ./app/secrets.dev.env
    volumes:
      - ./app:/opt/app:delegated
      - notused:/opt/app/node_modules

volumes:
  notused:
