#!/bin/bash -e

[ -z "$1" ] && { echo "ERROR: Please specify a service name."; exit 1; }
[[ -z "$COMPOSE_PROJECT_NAME" ]] && source "$(pwd)/project.env"

image="${COMPOSE_PROJECT_NAME}_$1"
instance=`docker ps -q -l -f ancestor="${image}" --format '{{.ID}} {{.Names}}'`

if [ ! -z "$instance" ]; then
    container=($instance)
    echo "Container: ${container[1]} (${container[0]})"
    docker exec -i -t "${container[0]}" /bin/bash
    exit 0
fi

echo -e "ERROR: Container matching image '${image}' not found.\n"
docker ps
exit 1
