FROM node:8-slim

ENV TSC_VERSION 2.9.1

ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

ARG PORT=3000
ENV PORT $PORT

ARG DEBUG_PORT=9229
ENV DEBUG_PORT $DEBUG_PORT

RUN mkdir -p /opt/app /opt/node_modules
RUN npm install -g typescript@$TSC_VERSION tsc-watch

ENV PATH /opt/node_modules/.bin:$PATH
ENV NODE_PATH /opt/app:/opt/node_modules

WORKDIR /opt
COPY ./package.json ./package-lock*.json ./
RUN npm install --quiet

WORKDIR /opt/app
COPY . .

ENV NODE_OPTIONS "--inspect-port=${DEBUG_PORT}"
CMD [ "npm", "run", "debug" ]
